#! /bin/bash
#
# lil: (or, Last Item Listed): Prints out just the name of the last file`
# listed in an ls -l directory listing. 
#
# Created: March 19, 2021
# Modifie┌: March 19, 2021
#
# by Eric Patton
#
##############################################################################

ls -l | tail -n1 | awk '{print $9}'

exit 0

