#! /bin/bash
#
# lmt: (or, Last Modified Thing): Prints out just the name of the last thing
# you modified in the currecnt directory. This differs from 'ls -1r' in that
# only the last file modified is printed, not a full directory listing.
#
# Created: February 1, 2021
# Modifie┌: March 19, 2021
# by Eric Patton
#
##############################################################################

PATTERN=$1

# To-Do: Add a help messgae for -h flag and friends.

ls -ltrh ${PATTERN} | tail -n1 | awk '{print $9}'

exit 0
