#! /bin/bash
#
# lrl: (or, Last Raster Listed): Prints out just the name of the last raster
# in a g.list type=raster listing. 
#
# Created: March 19, 2021
# Modifie┌: March 19, 2021
#
# by Eric Patton
#
##############################################################################

if  [ -z "$GISBASE" ] ; then
    echo "You must be in GRASS GIS to run this program."
    exit 1
fi

g.list type=rast mapset=. | tail -n1 

exit 0
