#! /bin/bash
#
# lvl: (or, Last Vector Listed): Prints out just the name of the last vector
# in a g.list type=vector listing. 
#
# Created: March 19, 2021
# Modifie┌: March 19, 2021
#
# by Eric Patton
#
##############################################################################

if  [ -z "$GISBASE" ] ; then
    echo "You must be in GRASS GIS to run this program."
    exit 1
fi

g.list type=vect mapset=. | tail -n1 

exit 0

