#! /bin/bash

INPUT_SUFFIX=$(echo $INPUT | cut -d'.' -f2)
INPUT_BASE=$(basename $INPUT .$INPUT_SUFFIX)
OUTPUT_TEXT=${INPUT_BASE}.txt 
OUTPUT_TIFF=${INPUT_BASE}.tif              
OUTPUT_GRID=${INPUT_BASE}.grd              
OUTPUT_GMT=${INPUT_BASE}.gmt
OUTPUT_RAST=${INPUT_BASE}_rast
OUTPUT_VECT=${INPUT_BASE}_vect
OUTPUT_XYZ=${INPUT_BASE}.xyz
OUTPUT_PS=${INPUT_BASE}.ps
OUTPUT_PDF=${INPUT_BASE}.pdf
OUTPUT_PNG=${INPUT_BASE}.png
OUTPUT_JPG=${INPUT_BASE}.jpg
OUTPUT_ASC=${INPUT_BASE}.asc
OUTPUT_MB1=${INPUT_BASE}.mb-1
OUTPUT_SHP=${INPUT_BASE}.shp
OUTPUT_POINTS=${INPUT_BASE}_points
OUTPUT_LINES=${INPUT_BASE}_lines
OUTPUT_BOUNDS_VECT=${INPUT_BASE}_bounds_vect
OUTPUT_BOUNDS_RAST=${INPUT_BASE}_bounds_rast
