#! /bin/bash
#
# mbc: A shorthand for calling mb.cleaning grid and mbgrdviz together.
#
# Created: March 26, 2021
# Modified: March 26, 2021
# by Eric Patton
#
##############################################################################

mb.cleaning_grid.sh datalistp.mb-1 && mbgrdviz -I cleaning_grid_$(date '+%b%d_%Y').grd

exit 0
