#! /bin/bash
#
# ptd: (or, Print Thiѕ Directory (name): Prints out just the name of the current
# directory name. Like pwd, but only the basename of the path.
#
# Created: March 19, 2021
# Modifie┌: March 19, 2021
#
# by Eric Patton
#
##############################################################################

basename $(pwd)

exit 0
