#! /bin/bash
#
# rml: (or, ReMove Locked files): Runs mbdatalist -Y on the current directory,
# removing all locked files.
#
# Created: March 26, 2021
# Modified: March 26, 2021
# by Eric Patton
#
##############################################################################

mbdatalist -F-1 -I datalist.mb-1 -Y | grep "Removing"

exit 0
