#! /bin/bash 
#
############################################################################
#
# MODULE:        mb.bckcst_process.sh 
# 
# AUTHOR:   	 Eric Patton, Geological Survey of Canada (Atlantic)
#		 		 <Eric dot Patton at Canada dot ca>
# 
# PURPOSE:       Script for batch processing backscatter
#		 		 
# Last Modified: June 3, 2022
#
############################################################################

SCRIPT=$(basename $0)

if  [ -z "$GISBASE" ] ; then
    echo "You must be in GRASS GIS to run this program."
    exit 1
fi

if [ "$#" -lt 2 -o "$1" == "-H" -o "$1" == "-h" -o "$1" == "--help" -o "$1" == "-help" ] ; then
	echo -e "\nusage: $SCRIPT datalist.mb-1 resolution [ reference_angle [30] ] [ priority value (1-8) [2], or priority filename ] \n"
	exit 0
fi

# What to do in case of user break:
exitprocedure()
{
	echo -e "\n\n$SCRIPT: User break or similar caught; Exiting.\n"
	exit 1
}

# Setup clean exit for Ctrl-C or similar breaks.
trap 'exitprocedure' 2 3 15


DATALIST=$1
RES=$2
REFERENCE_ANGLE=$3
PRIORITY=$4

[[ -z ${REFERENCE_ANGLE} ]] && REFERENCE_ANGLE=30

[[ -z ${PRIORITY} ]] && PRIORITY=2

# mbbackangle flag notes:
#  -A: Determines if beam amplitude (kind = 1) and/or sidescan (kind = 2) data
#  will be processed.
#
#  -Q: By  default,  mbbackangle does not use seafloor slopes in calculating the
# grazing angles for each amplitude beam and sidescan pixel. This option causes
# the program to calculate acrosstrack slopes from swath bathymetry, if
# available, and to factor these slopes into the grazing angle calculation for
# each data point.
#
# -N: The amplitude vs grazing angle table is calculated by binning the
# amplitude values according to their grazing angles and averaging the
# amplitudes within each bin. This option sets the number of grazing angle bins
# (nan‐ gle)  and the maximum angle considered (angle). The grazing angle
# function will be defined at nangle points spaced equally from -angle to
# +angle. The nangle value should be an odd integer so that the middle bin is
# cen‐ tered on the angle 0.0.  Default: nangle = 81, angle = 80.0.
#
# -R: refangle Sets the reference angle that will be used by mbprocess in
# applying the amplitude and/or sidescan correction tables generated by
# mbbackangle. Default: refangle = 30.0 degrees.
# 
# -G: kind/angle/max/nx/ny
# This option causes mbbackangle to output gridded histograms of the
# amplitude versus grazing angle data for each swath file processed.
# The program also generates a shellscript to produce a first-cut
# GMT postscript  plot of  the  histogram overlain by the amplitude
# versus grazing angle tables used by mbprocess.  The kind parameter
# indicates whether an amplitude (kind = 1) or sidescan (kind = 2)
# histogram is desired; the -G command must be given twice (once
# with kind = 1 and once with kind = 2) to generate both amplitude
# and sidescan histograms. The histogram grid consists of nx bins
# extending from -angle to +angle degrees in the x-dimension,  and
# ny bins extending from 0.0 to max in the y-dimension. The values
# of the histogram are normalized so that they sum to 1000.0 within
# each angle bin.
#

mbbackangle -I ${DATALIST} -A1 -Q -N87/80.0 -R${REFERENCE_ANGLE} -V
mbset -I ${DATALIST} -PAMPCORRFILE:${DATALIST}_tot.aga -PAMPCORRMODE:1 -PAMPCORRANGLE:${REFERENCE_ANGLE}
mbprocess -F-1 -I ${DATALIST} -C16 
mbdatalist -F-1 -I ${DATALIST} -Z

# mbmosaic flag notes:
#
# -A: datatype
# Sets the type of data to be read and mosaiced.
# datatype = 3, amplitude data will be mosaiced.
# datatype = 4, sidescan data will be mosaiced.
# datatype = 5, flat bottom grazing angle will be mosaiced.
# datatype = 6, acrosstrack grazing angle will be mosaiced.
# datatype = 7, acrosstrack slope will be mosaiced.
#
# -N: Causes grid cells with no data and no interpolation to be set to a value
# of NaN instead of the default value of 99999.9.  The NaN value is expected by
# GMT programs such grdview.
#
# -Y: Enables priortization of data points based on their apparent grazing
# angle, using this schema:
#
# priority_source = 1:
# Angle (deg)  Priority
# ---------------------
#  -60          1.0
#    0          0.0
#   60          1.0
#
# priority_source = 2:
# Angle (deg)  Priority
# ---------------------
#  -67          1.0
#    0          0.0
#   67          1.0 
#
# See the mbmosaic man page for more options. A custom priority table can also
# be used.  Here is the sample grazing angle priority values given in the
# mbmosaic manpage:
#
#  -60.0 0.2
#  -45.0 1.0
#  -15.0 0.8
#  -14.9 0.1
#  14.9 0.1
#  15.0 0.8
#  45.0 1.0
#  60.0 0.2
#
# -F: Turns on Gaussian weighted mean mosaicing. The priority_range value
# determines which data points are used in the mosaicing. The minimum priority
# threshold for each bin is the highest priority value found among the sam‐ ples
# in that bin minus the priority_range value.  Only samples with priorities
# greater than this threshold are used in the Gaussian weighted mean mosaicing.
# The default is to simply set each bin's value equal  to  the value of the
# highest priority sample in that bin.  The weight value, if present, causes
# priorities to be also used to weight values. A weight of 0 (the default)
# indicates priorities are not used as weights. A weight of 1 indicates the
# Gaussian weight of each value is multiplied by its priority to get the value
# weight. A weight of 2 indicates the Gaussian weight of each value is
# multiplied by the square of  its priority  to  get the value weight.

mbmosaic -I $(basename $DATALIST .mb-1)p.mb-1 -A3 -N -Y${PRIORITY} -F0.05/1 -E${RES}/${RES}/meters! -R$(mb.getregion) -JUTM20N -O BckSct_Y${PRIORITY}_refangle_${REFERENCE_ANGLE}_${RES}m -V

exit 0
